### ISSUE TITLE
Article sur la méthode API-first

### ISSUE THREAD

**Issue by FBerthelot** [la-veilleuse/la-veilleuse#11]
Voilà j'aimerai bien faire un article là dessus, la methode et les outils.
Comment ce que cela implique côté agilité, comment utiliser swagger etc.

**Comment by FBerthelot** [comment]
Non finalement ça ne me passion plus, I quit

**Comment by jgrenat** [comment]
:-1:

**Comment by FBerthelot** [comment]
Tu en voulait vraiment un ?

**Comment by jgrenat** [comment]
Nan, je m'en fous, mais une PR c'est comme une Promise que tu viens de rejeter !

**Comment by FBerthelot** [comment]
Ceci est une issue !

**Comment by jgrenat** [comment]
C'est la même !
